### PR TITLE
fix #3 append root slash for unix when absolute paths are provided

### LINKED ISSUE #3: prefix slash hard coded
thanks again for merging my previous PR.
I added a note concerning the prefix "/" you hard-coded unless the "~" is found.
I think this should not be there, but I may miss something. 

this also is the reason for appveyor to fail: 
```
: normalizePath(file.path("/", "C:", "Users", "appveyor", "AppData", "Local", "Temp", 
         "1", "RtmpCIdudx", "RLIBS_7d453ec408d", "reformatFilePath", "rstudio", "addins.dcf"), 
         mustWork = TRUE)
```

so at least it should use `.Platform$file.sep` to avoid slashes in windows.

### PR DESCRIPTION
**Pull request by ginolhac**
should fix #3 . trying... let's see what travis and appveyor say

### CODE REVIEW

**Comment by ginolhac** [comment]
sounds ok then. Adding a prefix slash ONLY for unix platform and ONLY when initially provided by the user

**Comment by konradzdeb** [comment]
Yup, that should do it. I'm wondering whether maybe we should use regex from [`R.utils::isAbsolutePath`](https://github.com/HenrikBengtsson/R.utils/blob/master/R/isAbsolutePath.R) which is:

```r
if (regexpr("^~", pathname) != -1L)
```

is there a situation where this would make a materia difference?

**Comment by ginolhac** [comment]
this is too technical for me, I cannot foresee a difference. Should we just leave it as it is and be the test ourselves?

**Comment by konradzdeb** [comment]
Yes, of course. I was just wondering why they did like that :)

**Pull request merged**
